### ISSUE TITLE
get_best_candidates in snli.py

### ISSUE THREAD

**Issue by JieyuZhao** [Eric-Wallace/universal-triggers#15]
Hi,

In snli.py file, I'm wondering why _**get_best_candidates()**_ function extracts the best candidate with the largest loss but at the same time, the model extracts candidates that can minimize model's loss (_**hotflip_attack()**_ function with increase_loss=False)? Shouldn't the best candidate also minimize the loss? Thanks!

**Comment by Eric-Wallace** [comment]
Hi! This part is ugly sorry.

Overall, what the code for SNLI does is a targeted attack to flip entailment examples to contradiction. We first filter the examples to only ones with the entailment label https://github.com/Eric-Wallace/universal-triggers/blob/ed657674862c965b31e0728d71765d0b6fe18f22/snli/snli.py#L34
Next what I do is I compute the gradient but pass in the target label of contradiction https://github.com/Eric-Wallace/universal-triggers/blob/ed657674862c965b31e0728d71765d0b6fe18f22/snli/snli.py#L63 which is used instead of the entailment label during loss calculation. So we should set increase_loss to be False because we want the examples to be more like the target label. 

The main ugliness is that when I actually evaluate the candidates, I don’t pass the contradiction target label in https://github.com/Eric-Wallace/universal-triggers/blob/ed657674862c965b31e0728d71765d0b6fe18f22/snli/snli.py#L81 So, the examples have the entailment label now, so we actually want to increase the loss of them. Thats why theres a change in whether we increase or decrease.

What the code should probably be doing is passing in the target label when I am evaluating the candidates, and then take the min loss as you said.

**Comment by JieyuZhao** [comment]
I see. That makes sense. Thank you!
