### ISSUE TITLE
Any ELMO code examples?

### ISSUE THREAD

**Issue by SwapnilDreams100** [Eric-Wallace/universal-triggers#18]
Hi,
would appreciate code examples to use character embeddings of ELMO for SST -LSTM or SNLI -DA

**Comment by Eric-Wallace** [comment]
Hi, the ELMO code I had was very messy so it never made it into the final release. If you want to do ELMO, you will have to code it yourself. However, I would probably not recommend doing any ELMO experiments, as it would be way simpler and more relevant to do experiments on pretrained transformer models such as BERT or ALBERT.

**Comment by SwapnilDreams100** [comment]
Ok thanks a lot for your quick revert! Another issue I had was regarding the decomposable attention with glove model.
Due to a projection layer[300->200] in the Embedding layer, while the weight matrix has a dimension of [vocab_size, 300], the input gradients had a dimension of only [seq_len, 200], causing a mismatch in Hopflip. Would really appreciate if you could share your solution to this.

**Comment by Eric-Wallace** [comment]
Ah, I actually never used the Decomposable Attention model in the gradient computation. I only ever generated the attacks with the ESIM model and then transfered them to the DA model. The reason this issue arises is because there is a backward hook applied to the TextFieldEmbedder from AllenNLP at this line https://github.com/Eric-Wallace/universal-triggers/blob/ed657674862c965b31e0728d71765d0b6fe18f22/utils.py#L34. 

That embedder encompasses _both_ the weight matrix and the projection layer. What you'd want to do is to apply the hook to _only_ the embedding layer of that embedder module.

**Comment by SwapnilDreams100** [comment]
Yeah I tried to do that, didnt work for some reason. Anyway thanks a lot! Im closing the issue.
