### ISSUE TITLE
A little confused about the training process

### ISSUE THREAD

**Issue by dwaydwaydway** [Eric-Wallace/universal-triggers#5]
For snli task, if i sample the subset of which the labels are 'entailment' and attack toward the same class(increase_loss=Flase), the accuracy should get higher right? cause we minimize the loss between the input and the target 'entailment', which is the true label.

That wasn't the case though, the accuracy drops.

**Comment by Eric-Wallace** [comment]
Hi!. Ah, it looks like the SNLI code is hardcoded to make things bigger. It can be fixed with the following.

First, just to make sure, before making any changes, it should be `dataset_label_filter` = 'entailment', `target_label` = '0', and `increase_loss`=False.

Now, `increase_loss` will tell the gradient-based attack to reverse the sign. But, once you get the candidates back from the gradient-based attack, it then queries them using the model with `get_best_candidates`. Currently, `get_best_candidates` is hardcoded to increase the loss. Its a simple change, 

https://github.com/Eric-Wallace/universal-triggers/blob/3932b4d2d5976085d49407326ae20cabf02403f2/utils.py#L130 This should be nsmallest, not nlargest. and same with this https://github.com/Eric-Wallace/universal-triggers/blob/3932b4d2d5976085d49407326ae20cabf02403f2/utils.py#L138

https://github.com/Eric-Wallace/universal-triggers/blob/3932b4d2d5976085d49407326ae20cabf02403f2/utils.py#L139 and this should be a min, not a max.

**Comment by Eric-Wallace** [comment]
Let me know if that fixes things! @dwaydwaydway

**Comment by dwaydwaydway** [comment]
I see, now I understand. Thanks for your replay!
