### ISSUE TITLE
Questions regarding sentiment words

### ISSUE THREAD

**Issue by dugu9sword** [Eric-Wallace/universal-triggers#6]
Hello Eric, in your paper you wrote that a sentiment word list is used to filter the words  to substitute, but I could not find related code in the repository. Maybe the reason is that it is not important in generating the trigger words?

**Comment by Eric-Wallace** [comment]
Hi, sorry for the delay. I was on vacation for the holidays.

You are correct. I left it out because it added some complexity that isn't quite necessary.

If you run the sentiment analysis attack against a good model (e.g., BERT), you will often see positive/negative sentiment words appearing in the attack. If you want to prevent this from happening, I suggest adding a word list. I can share the code if you need it.

**Comment by Eric-Wallace** [comment]
Going to close this issue, feel free to reopen if you need more help!

**Comment by Danielpark1239** [comment]
Hi Eric, I'm looking at your paper for a school project and was wondering if you had the code to filter positive/negative sentiment words from the hotflip attack. Any help would be appreciated!
